#
# SPDX-FileCopyrightText: Copyright 2022 Arm Limited and/or its affiliates <open-source-office@arm.com>
# SPDX-License-Identifier: MIT
#

version: "3.8"
services:
  api:
    image: "${DOCKERHUB_USERNAME}/ml-app-pi:latest"
    build:
     context: .
     dockerfile: ./dockers/ml_api/Dockerfile
    network_mode: "host"

  server:
    image: "${DOCKERHUB_USERNAME}/triton-server:latest"
    build:
      context: .
      dockerfile: ./dockers/triton_server/Dockerfile
    volumes:
      - ./models:/models
    network_mode: "host"
