# This is a basic workflow to help you get started with Actions

name: Publish Docker Image

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  lint:
      runs-on: ubuntu-18.04

        # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
      - uses: actions/checkout@v1
      - name: Setup Python environment
        uses: actions/setup-python@v1.1.1
      - name: Install requirements
        run: pip install --quiet --requirement requirements.txt
      - name: Lint code
        run: |
          flake8 --ignore=E501,E231 *.py
          pylint --disable=C0301 --disable=C0326 test_app.py
      - name: Run unit tests
        run: |
          python -m unittest --verbose --failfast
  build_image:
        needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
         context: .
         file: ./Dockerfile
         push: true
         tags: ${{ secrets.DOCKERHUB_USERNAME }}/mlapp-docker:latest

