# This is a basic workflow to help you get started with Actions

name: Publish Docker Image

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build_image:
    #    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
         context: .
         file: ./Dockerfile
         push: true
         tags: ${{ secrets.DOCKERHUB_USERNAME }}/ml-docker:latest

