# This is a basic workflow to help you get started with Actions

name: Publish Docker Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  release:
    types:
      - published

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_push_image:
    name: Build docker image and push to repository
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: crazy-max/ghaction-docker-meta@v1
        name: Docker meta
        id: docker_meta
        with:
          images: ghcr.io/Elm8116/docker-ML-app
          tag-sha: true
          tag-edge: false
          tag-latest: true
      - uses: docker/setup-qemu-action@v1
        name: Setup QEMU

      - uses: docker/login-action@v1
        name: Login to GHCR
        with:
          registry: ghcr.io
          username: ${{ Elm8116 }}
          password: ${{ secrets.GHCR_PAT }}

      - uses: docker/build-push-action@v2
        name: Build image
        with:
          tag: ${{ steps.docker_meta.outputs.tags }}
          file: ./Dockerfile

      - uses: docker/build-push-action@v2
        name: Push image
        with:
          push: true
          tag: ${{ steps.docker_meta.outputs.tags }}
          file: ./Dockerfile


#

