name: Publish Docker image to Docker Hub and GitHub packages

on:
  release:
    types: [published]

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
     - name: Check out the repo
       uses: actions/checkout@feb3d0b6c6d7e5647017cbec1b0b8c8bbb60396b 

     - name: Login to Docker Hub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Login to Container Registry
       uses: docker/login-action@feb3d0b6c6d7e5647017cbec1b0b8c8bbb60396b 
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GHCR_PAT }}
     - name: Extract metadata (tags, labels) for Docker
       id: meta
       uses: docker/metadata-action@feb3d0b6c6d7e5647017cbec1b0b8c8bbb60396b 
       with:
         images: |
           ml-app-docker/elham8116
           ghcr.io/${{ github.repository }}

     - name: Build and push Docker images
       uses: docker/build-push-action@feb3d0b6c6d7e5647017cbec1b0b8c8bbb60396b
       with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
