name: Publish Docker Image on Docker Hub

on:
  push:
    branches: [main]

jobs:
  build_image:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
#       - name: Set up QEMU        
#         uses: docker/setup-qemu-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push to docker hub
        uses: docker/build-push-action@v2
        with:
         context: .
         file: ./Dockerfile
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/ml-app-image-self-hosted:latest

  test_image:
    needs: [build_image]
    runs-on: self-hosted
    steps:
    - name: Run Unit Test
      run: docker run -d -p 0.0.0.0:8080:8080 "${{ secrets.DOCKER_USERNAME }}/ml-app-image-self-hosted:latest" -m unittest --verbose --failfast
