name: Build and Publish Docker Image on Docker Hub
on:
  push:
    branches: [main]
    paths-ignore:
      - '**/README.md'
jobs:
  build_image:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build the docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/ml-app-pi:latest

      - name: Invoke Server
        run: docker run -v ${GITHUB_WORKSPACE}/models:/models -d --network host elham8116/inferenceserver ./invoke_server.sh
        
      - name: Run unit test inside docker container
        run: docker run "${{ secrets.DOCKER_USERNAME }}/ml-app-pi:latest" -m unittest --verbose --failfast

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
            
      - name: Push Image to Docker Hub
        run:
          docker push ${{ secrets.DOCKER_USERNAME }}/ml-app-pi:latest
            
  deploy:
    needs: [build_image]
    runs-on: self-hosted
    steps:
     - name: stop all containers
       run: ./stop_containers.sh

     - name: Invoke Server
       run: docker run -v ${GITHUB_WORKSPACE}/models:/models -d --network host elham8116/inferenceserver ./invoke_server.sh

     - name: run the container on virtual raspberry pi 
       run:
        docker run -d --network host ${{ secrets.DOCKER_USERNAME }}/ml-app-pi:latest
      
